### ISSUE TITLE
Failed to start BepInEx

### ISSUE THREAD

**Issue by niizam** [Kyuukai/Heaven-Burns-Red-Translation-Project#11]
Yesterday the translator worked fine. But today I got "Failed to start BepInEx" error message when opening the game.
Do you guys have any workaround for this problem?
Or should I open an issue to BepInEx repo instead?

![image](https://github.com/user-attachments/assets/9d7cf2a6-783b-4659-95a0-867d1c05a88c)
Here's the `preloader_20240727_221759_423.log`:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2Cpp.GetMethodPointer(String imageName, Il2CppMethodDefinition methodDef) in C:\Users\_\source\repos\BepInEx\Il2CppDumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 318
   at Il2CppDumper.DummyAssemblyGenerator..ctor(Il2CppExecutor il2CppExecutor, Boolean addToken) in C:\Users\_\source\repos\BepInEx\Il2CppDumper\Il2CppDumper\Utils\DummyAssemblyGenerator.cs:line 304
   at Il2CppDumper.ExtensionMethods.GenerateCecilAssemblies(Metadata metadata, Il2Cpp il2Cpp, List`1& Assemblies) in C:\Users\_\source\repos\BepInEx\Il2CppDumper\Il2CppDumper\ExtensionMethods.cs:line 180
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.Initialize() in C:\Users\_\source\repos\BepInEx\Runtimes\Unity\BepInEx.Unity.IL2CPP\Il2CppInteropManager.cs:line 232
   at BepInEx.Unity.IL2CPP.Preloader.Run() in C:\Users\_\source\repos\BepInEx\Runtimes\Unity\BepInEx.Unity.IL2CPP\Preloader.cs:line 67
   at BepInEx.Unity.IL2CPP.UnityPreloaderRunner.PreloaderMain() in C:\Users\_\source\repos\BepInEx\Runtimes\Unity\BepInEx.Unity.IL2CPP\UnityPreloadRunner.cs:line 29
   at Doorstop.Entrypoint.Start() in C:\Users\_\source\repos\BepInEx\Runtimes\Unity\BepInEx.Unity.IL2CPP\DoorstopEntrypoint.cs:line 39
   ```

**Comment by Kyuukai** [comment]
It seems the latest HBR update broke it.
I think it'd be better to open an issue to BepInEx repo instead as I am just using the tool to translate

**Comment by niizam** [comment]
> It seems the latest HBR update broke it. I think it'd be better to open an issue to BepInEx repo instead as I am just using the tool to translate

In the README, which version of BepInEx and its plugins are included?

**Comment by Kyuukai** [comment]
BepInEx 6.0.0, though I do not remember which build it was
